apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: depot
  namespace: depot
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2g"
spec:
  ingressClassName: nginx
  rules:
  - host: depot.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: depot-service
            port:
              number: 80
