apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: depot-pvc
  namespace: depot
  labels:
    app: depot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
